---
name: Text-WordDiff
version: 0.02
author:
  - David Wheeler <david@kineticode.com>
abstract: Track changes between documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Algorithm::Diff: 1.19
  HTML::Entities: 0
  Term::ANSIColor: 0
build_requires:
  File::Spec: 0
  Test::Simple: 0.17
provides:
  Text::WordDiff:
    file: lib/Text/WordDiff.pm
    version: 0.02
  Text::WordDiff::ANSIColor:
    file: lib/Text/WordDiff/ANSIColor.pm
    version: 0.02
  Text::WordDiff::Base:
    file: lib/Text/WordDiff.pm
  Text::WordDiff::HTML:
    file: lib/Text/WordDiff/HTML.pm
    version: 0.02
generated_by: Module::Build version 0.2702
