---
name: Text-WordDiff
version: 0.03
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Track changes between documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Algorithm::Diff: 1.19
  HTML::Entities: 0
  Term::ANSIColor: 0
build_requires:
  File::Spec: 0
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Text::WordDiff:
    file: lib/Text/WordDiff.pm
    version: 0.03
  Text::WordDiff::ANSIColor:
    file: lib/Text/WordDiff/ANSIColor.pm
    version: 0.03
  Text::WordDiff::Base:
    file: lib/Text/WordDiff.pm
  Text::WordDiff::HTML:
    file: lib/Text/WordDiff/HTML.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
